// Generated by LiveScript 1.4.0
/**
 * User: Roy
 * Date: 2016/5/31
 * Time: 16:52
 */
var MyGaleraClient, pool, count, now;
MyGaleraClient = require('../index');
pool = MyGaleraClient.createPool([
  {
    host: '192.168.1.221',
    port: 3306,
    connectionLimit: 2
  }, {
    host: '192.168.1.223',
    port: 3306,
    connectionLimit: 3
  }
], 'testuser', '123123', 'test1');
count = 0;
now = Date.now();
setInterval(function(){
  var thisCount, sql;
  console.log("");
  count += 1;
  thisCount = count;
  sql = "";
  if (thisCount <= 60) {
    sql = "insert into MyClass (name,sex,degree) values('" + now + "-" + thisCount + "',0,0)";
  } else {
    sql = "select count(*) from MyClass where name like '%" + now + "%'";
  }
  console.log(">>>>>>>> runCount = ", thisCount);
  pool.query(sql, function(error, results, fields){
    console.log("out error = ", error);
    console.log("out results = ", results);
    console.log("<<<<<<<< runCount = ", thisCount);
  });
}, 1000);